media:
  - name: images
    label: Images
    input: images
    output: /images

  - name: cases_images
    label: Cases images
    input: images/cases
    output: /images/cases

  - name: icons
    label: Icons
    input: images/icons
    output: /images/icons
    
content:
  - name: general
    label: General
    type: file
    path: content/general.json
    fields:
      # Hero section
      - name: hero
        label: Hero
        type: object
        fields:
          - { name: image, label: Image, type: image, required: true }
          - name: firstName
            label: First name
            type: object
            fields:
              - { name: en, label: English, type: string, required: true }
              - { name: uk, label: Ukrainian, type: string, required: true }
          - name: middleName
            label: Middle name
            type: object
            fields:
              - { name: en, label: English, type: string, required: true }
              - { name: uk, label: Ukrainian, type: string, required: true }
          - name: title
            label: Title
            type: object
            fields:
              - { name: en, label: English, type: string, required: true }
              - { name: uk, label: Ukrainian, type: string, required: true }
          - name: subtitle
            label: Subtitle
            type: object
            fields:
              - { name: en, label: English, type: string, required: true }
              - { name: uk, label: Ukrainian, type: string, required: true }
          - name: actionText
            label: Action text
            type: object
            fields:
              - { name: en, label: English, type: string, required: true }
              - { name: uk, label: Ukrainian, type: string, required: true }
          - name: descriptionText
            label: Description text
            type: object
            fields:
              - { name: en, label: English, type: string, required: true }
              - { name: uk, label: Ukrainian, type: string, required: true }
          - name: actionButtonText
            label: Action Button Text
            type: object
            fields:
              - { name: en, label: English, type: string, required: true }
              - { name: uk, label: Ukrainian, type: string, required: true }
          - name: drawerTitle
            label: Drawer title (with contacts)
            type: object
            fields:
              - { name: en, label: English, type: string, required: true }
              - { name: uk, label: Ukrainian, type: string, required: true }
          - name: drawerSubitle
            label: Drawer subtitle (with contacts)
            type: object
            fields:
              - { name: en, label: English, type: string, required: true }
              - { name: uk, label: Ukrainian, type: string, required: true }
              
      # About Section
      - name: about
        label: About
        type: object
        fields:
          - name: items
            label: Items
            type: object
            list: true
            fields:
              - name: title
                label: Title
                type: object
                fields:
                  - { name: en, label: English, type: string, required: true }
                  - { name: uk, label: Ukrainian, type: string, required: true }
              - name: body
                label: Body
                type: object
                fields:
                  - { name: en, label: English, type: rich-text, required: true }
                  - { name: uk, label: Ukrainian, type: rich-text, required: true }

      # Process Section
      - name: process
        label: Process
        type: object
        fields:
          - name: mainDescription
            label: Main description
            type: object
            fields:
              - { name: en, label: English, type: string, required: true }
              - { name: uk, label: Ukrainian, type: string, required: true }
          - name: items
            label: Items (max = 6)
            type: object
            list: true
            fields:
              - name: title
                label: Title
                type: object
                fields:
                  - { name: en, label: English, type: string, required: true }
                  - { name: uk, label: Ukrainian, type: string, required: true }
              - name: body
                label: Body
                type: object
                fields:
                  - { name: en, label: English, type: rich-text, required: true }
                  - { name: uk, label: Ukrainian, type: rich-text, required: true }

      # Contacts Section
      - name: contacts
        label: Contacts
        type: object
        fields:
          - name: items
            label: Items
            type: object
            list: true
            fields:
              - { name: title, label: Title, type: string, required: true }
              - { name: label, label: Label, type: string, required: true }
              - { name: link, label: Link, type: string, required: true }
              - name: icon
                label: Icon
                type: image
                options:
                  media: icons
                  extensions: [svg]
              
      # Footer Section
      - name: footer
        label: Footer
        type: object
        fields:
          - name: pc
            label: Image for desktop (min-1407x310px | best-2709x506px)
            type: object
            fields:
              - { name: image, label: Image (.png), type: image, required: true }
          - name: mob
            label: Image for mobile (min-411x214px | best-704x344px)
            type: object
            fields:
              - { name: image, label: Image (.png), type: image, required: true }

  - name: cases
    label: Cases
    type: file
    path: content/cases.json
    fields:
      # Cases Section
      - name: items
        label: Cases Section (max = 6)
        type: object
        list: true
        fields:
          - name: image
            label: Image
            type: image
            required: true
            options:
              media: cases_images
          - name: title
            label: Title
            type: object
            fields:
              - { name: en, label: English, type: string, required: true }
              - { name: uk, label: Ukrainian, type: string, required: true }
          - name: body
            label: Body
            type: object
            fields:
              - { name: en, label: English, type: string, required: true }
              - { name: uk, label: Ukrainian, type: string, required: true }
          - { name: link, label: Link, type: string, required: true }
