media:
  - name: images
    label: Images
    input: images
    output: /images

  - name: cases_images
    label: Cases images
    input: images/cases
    output: /images/cases
    
content:
  - name: general
    label: General
    type: file
    path: content/general.json
    fields:
      # About Section
      - name: about
        label: About
        type: object
        fields:
          - { name: photo, label: Photo, type: image, required: true }
          - name: body
            label: Body
            type: object
            fields:
              - { name: en, label: English, type: rich-text, required: true }
              - { name: uk, label: Russian, type: rich-text, required: true }
              
      # Contacts Section
      - name: contacts
        label: Contacts
        type: object
        fields:
          - name: items
            label: Items
            type: object
            list: true
            fields:
              - { name: title, label: Title, type: string, required: true }
              - { name: name, label: Name, type: string, required: true }
              - { name: link, label: Link, type: string, required: true }
              - { name: icon, label: Icon SVG, type: string, required: true }

      # Skills Section
      - name: skills
        label: Skills
        type: object
        fields:
          - name: development
            label: Development
            type: object
            fields:
              - name: items
                label: Items
                type: object
                list: true
                fields:
                  - { name: title, label: Title, type: string, required: true }
                  - { name: icon, label: Icon SVG, type: string, required: true }
                  # - { name: icon, label: Icon, type: image, required: true, options: { media: vectors, extensions: [svg] } }

          - name: design
            label: Design
            type: object
            fields:
              - name: items
                label: Items
                type: object
                list: true
                fields:
                  - { name: title, label: Title, type: string, required: true }
                  - { name: icon, label: Icon SVG, type: string, required: true }
                  # - { name: icon, label: Icon, type: image, required: true, options: { media: vectors, extensions: [svg] } }

  - name: cases
    label: Cases
    type: file
    path: content/cases.json
    fields:
      # Cases Section
      - name: cases_section
        label: Cases Section
        type: object
        fields:
          - name: title
            label: Section Title
            type: object
            fields:
              - { name: en, label: English, type: string, required: true }
              - { name: uk, label: Ukrainian, type: string, required: true }
          - name: items
            label: Items
            type: object
            list: true
            fields:
              - name: image
                label: Image
                type: image
                required: true
                options:
                  media: cases_images
              - name: title
                label: Title
                type: object
                fields:
                  - { name: en, label: English, type: string, required: true }
                  - { name: uk, label: Ukrainian, type: string, required: true }
              - name: body
                label: Body
                type: object
                fields:
                  - { name: en, label: English, type: string, required: true }
                  - { name: uk, label: Ukrainian, type: string, required: true }
              - { name: link, label: Link, type: string, required: true }
  
      # Services Section
      - name: services
        label: Services Section
        type: object
        list: true
        fields:
          - name: image
            label: Image
            type: image
            required: true
            options:
              media: cases_images
          - name: title
            label: Title
            type: object
            fields:
              - { name: en, label: English, type: string, required: true }
              - { name: uk, label: Ukrainian, type: string, required: true }
          - name: body
            label: Body
            type: object
            fields:
              - { name: en, label: English, type: rich-text, required: true }
              - { name: uk, label: Ukrainian, type: rich-text, required: true }
